### ISSUE TITLE
Google Fit not show Steps, time, calories

### ISSUE THREAD

**Issue by trantuan4889** [hemantkamalakar/haconfigs#4]
My Hass not show information Steps, time, calories.
Only
sensor.google_fit_distance | 0.0 | friendly_name: Google Fit Distance unit_of_measurement: km last_updated: unknown
-- | -- | --
sensor.google_fit_height | 170.0 | friendly_name: Google Fit Height unit_of_measurement: cm last_updated: 1551689627
sensor.google_fit_weight | 52.4 | friendly_name: Google Fit Weight unit_of_measurement: Kg last_updated: 1551689627
Pls help me config  
P/s: Can you add heart rate information?

**Comment by hemantkamalakar** [comment]
Hello @trantuan4889 ,
Did you tried deleting the .google_fit.token file and restarting home-assistant?
This will take you to the Google page for granting permissions to your Google Fit data and recreate the token.

**Comment by trantuan4889** [comment]
ok, I fixed. Can you add heart rate information?

**Comment by hemantkamalakar** [comment]
Actually I am using Mi band 2 and heart rate data from Mi fit to Google fit is not being synced. I will check if I can add Heart rate data using Google Fit REST API.

**Comment by hemantkamalakar** [comment]
@trantuan4889  I have added Heart rate information also. Let me know if I can close this issue.
